"""Add sanitary_registration to ProductBatch

Revision ID: 0547f10f60a1
Revises: 2b796e21f434
Create Date: 2026-05-01 01:30:33.886567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0547f10f60a1'
down_revision = '2b796e21f434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sanitary_registration', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_batch', schema=None) as batch_op:
        batch_op.drop_column('sanitary_registration')

    # ### end Alembic commands ###
