"""add postal_code to company

Revision ID: 120904668044
Revises: e120702bcea1
Create Date: 2026-01-08 16:20:19.782621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120904668044'
down_revision = 'e120702bcea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postal_code', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('postal_code')

    # ### end Alembic commands ###
