"""Add InvoiceFolioCounter table for automatic folio tracking

Revision ID: 139f1c0a0650
Revises: 1c37ba14b6cc
Create Date: 2026-01-07 23:01:07.794110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139f1c0a0650'
down_revision = '1c37ba14b6cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_folio_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('serie', sa.String(length=25), nullable=False),
    sa.Column('current_folio', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'serie', name='unique_folio_per_company_serie')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_folio_counter')
    # ### end Alembic commands ###
