"""Initial migration with all tables

Revision ID: 1bc866e3ec51
Revises: 
Create Date: 2025-12-10 00:15:21.443465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc866e3ec51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index('idx_invoice_supplier')
        batch_op.create_foreign_key('fk_invoice_supplier', 'supplier', ['supplier_id'], ['id'])

    with op.batch_alter_table('movement', schema=None) as batch_op:
        batch_op.drop_index('idx_movement_category')
        batch_op.drop_index('idx_movement_invoice_unique')
        batch_op.create_foreign_key('fk_movement_category', 'category', ['category_id'], ['id'])

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_index('idx_supplier_rfc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.create_index('idx_supplier_rfc', ['rfc'], unique=False)

    with op.batch_alter_table('movement', schema=None) as batch_op:
        batch_op.drop_constraint('fk_movement_category', type_='foreignkey')
        batch_op.create_index('idx_movement_invoice_unique', ['invoice_id'], unique=1)
        batch_op.create_index('idx_movement_category', ['category_id'], unique=False)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_constraint('fk_invoice_supplier', type_='foreignkey')
        batch_op.create_index('idx_invoice_supplier', ['supplier_id'], unique=False)

    # ### end Alembic commands ###
