"""Add inventory COFEPRIS fields

Revision ID: 1c37ba14b6cc
Revises: a08bb8b316b7
Create Date: 2026-01-04 11:56:45.538498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c37ba14b6cc'
down_revision = 'a08bb8b316b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('initial_stock', sa.Integer(), nullable=True),
    sa.Column('current_stock', sa.Integer(), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('doctor_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('doctor_license', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('patient_name', sa.String(length=150), nullable=True))
        batch_op.create_foreign_key('fk_inventory_transaction_batch_id', 'product_batch', ['batch_id'], ['id'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sanitary_registration', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_controlled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('active_ingredient', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('presentation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('therapeutic_group', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('unit_measure', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('unit_measure')
        batch_op.drop_column('therapeutic_group')
        batch_op.drop_column('presentation')
        batch_op.drop_column('active_ingredient')
        batch_op.drop_column('is_controlled')
        batch_op.drop_column('sanitary_registration')

    with op.batch_alter_table('inventory_transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('patient_name')
        batch_op.drop_column('doctor_license')
        batch_op.drop_column('doctor_name')
        batch_op.drop_column('batch_id')

    op.drop_table('product_batch')
    # ### end Alembic commands ###
