"""add perm_inventory_admin to user_company_access

Revision ID: 2552c4ce8c3b
Revises: a202c4351aa8
Create Date: 2026-04-17 14:33:48.126701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2552c4ce8c3b'
down_revision = 'a202c4351aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_company_access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perm_inventory_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_company_access', schema=None) as batch_op:
        batch_op.drop_column('perm_inventory_admin')

    # ### end Alembic commands ###
