"""Add status_sat to Invoice

Revision ID: 2b796e21f434
Revises: 2552c4ce8c3b
Create Date: 2026-04-22 19:43:42.936891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b796e21f434'
down_revision = '2552c4ce8c3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_sat', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('status_sat')

    # ### end Alembic commands ###
