"""Add scanned_at scanned_by to exit_order_detail

Revision ID: 42b0af53c8a7
Revises: a14623e8c25e
Create Date: 2026-02-10 06:19:22.024097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42b0af53c8a7'
down_revision = 'a14623e8c25e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exit_order_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scanned_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('scanned_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_exit_detail_scanned_by', 'user', ['scanned_by_id'], ['id'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_product_supplier', 'supplier', ['preferred_supplier_id'], ['id'])
        batch_op.create_foreign_key('fk_product_laboratory', 'laboratory', ['laboratory_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_laboratory', type_='foreignkey')
        batch_op.drop_constraint('fk_product_supplier', type_='foreignkey')

    with op.batch_alter_table('exit_order_detail', schema=None) as batch_op:
        batch_op.drop_constraint('fk_exit_detail_scanned_by', type_='foreignkey')
        batch_op.drop_column('scanned_by_id')
        batch_op.drop_column('scanned_at')

    # ### end Alembic commands ###
