"""add_created_by_to_inventory_transaction

Revision ID: 7a9316d1d3c5
Revises: 42b0af53c8a7
Create Date: 2026-03-04 04:31:16.071592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a9316d1d3c5'
down_revision = '42b0af53c8a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_inv_tx_created_by', 'user', ['created_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_transaction', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inv_tx_created_by', type_='foreignkey')
        batch_op.drop_column('created_by_id')

    # ### end Alembic commands ###
