"""add_invoice_xml_fields

Revision ID: a08bb8b316b7
Revises: a54e8d4ff9d3
Create Date: 2026-01-04 11:34:59.602069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a08bb8b316b7'
down_revision = 'a54e8d4ff9d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serie', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('folio', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('lugar_expedicion', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('no_certificado', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sello', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('certificado', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('regimen_fiscal_emisor', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('regimen_fiscal_receptor', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('domicilio_fiscal_receptor', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('fecha_timbrado', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rfc_prov_certif', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sello_sat', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('no_certificado_sat', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('no_certificado_sat')
        batch_op.drop_column('sello_sat')
        batch_op.drop_column('rfc_prov_certif')
        batch_op.drop_column('fecha_timbrado')
        batch_op.drop_column('domicilio_fiscal_receptor')
        batch_op.drop_column('regimen_fiscal_receptor')
        batch_op.drop_column('regimen_fiscal_emisor')
        batch_op.drop_column('certificado')
        batch_op.drop_column('sello')
        batch_op.drop_column('no_certificado')
        batch_op.drop_column('lugar_expedicion')
        batch_op.drop_column('folio')
        batch_op.drop_column('serie')

    # ### end Alembic commands ###
