"""add_laboratory_sanitary_registrations

Revision ID: a202c4351aa8
Revises: d5cd8ec841e9
Create Date: 2026-03-21 02:30:48.547267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a202c4351aa8'
down_revision = 'd5cd8ec841e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laboratory_sanitary_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laboratory_sanitary_registration')
    # ### end Alembic commands ###
