"""add_product_categories_and_packaging

Revision ID: d5cd8ec841e9
Revises: d3c021db997c
Create Date: 2026-03-21 02:09:17.516914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5cd8ec841e9'
down_revision = 'd3c021db997c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requires_cofepris', sa.Boolean(), nullable=True),
    sa.Column('requires_batch_tracking', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='unique_product_category_per_company')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('packaging_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('units_per_package', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sell_by', sa.String(length=10), nullable=True))
        batch_op.create_foreign_key('fk_product_category_id', 'product_category', ['category_id'], ['id'])

    with op.batch_alter_table('purchase_order_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_unit', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('package_quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('loose_quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('packages_received', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('loose_received', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_detail', schema=None) as batch_op:
        batch_op.drop_column('loose_received')
        batch_op.drop_column('packages_received')
        batch_op.drop_column('loose_quantity')
        batch_op.drop_column('package_quantity')
        batch_op.drop_column('order_unit')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_category_id', type_='foreignkey')
        batch_op.drop_column('sell_by')
        batch_op.drop_column('units_per_package')
        batch_op.drop_column('packaging_type')
        batch_op.drop_column('category_id')

    op.drop_table('product_category')
    # ### end Alembic commands ###
